name: test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run lint
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build docker image
        run: docker build -t my-first-github-actions-wf:latest .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/my-first-github-actions-wf
          tags: |
            type=raw, value=prod
            type=raw, value=main, enable={{is_default_branch}}
            type=ref,event=tag
            type=sha
      - name: print metadata
        run: echo "tags=${{ steps.meta.outputs.tags }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker-push
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Deploy to production
        run: curl -X POST "${{ secrets.RENDER_PROD_DEPLOY_HOOK }}"

  docker-push-dev:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image for development
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-first-github-actions-wf:dev

  deploy-dev:
    runs-on: ubuntu-latest
    needs: docker-push-dev
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Deploy to development
        run: curl -X POST "${{ secrets.RENDER_DEV_DEPLOY_HOOK }}"